# Use the official image as a parent image
# FROM mcr.microsoft.com/dotnet/sdk:8.0
FROM ghcr.io/shimat/opencvsharp/ubuntu22-dotnet6-opencv4.7.0:20230114

# Set the working directory
WORKDIR /workspace

# Copy the current directory contents into the container at /workspace
COPY . /workspace

# Install cURL
RUN apt-get update && apt-get install -y curl

RUN apt-get update && \
    apt-get install -y dotnet-sdk-8.0

# Expose ports
EXPOSE 5000
EXPOSE 5001

# Define the entry point for the container
CMD ["dotnet", "run"]